### ISSUE TITLE
J2C Async

### ISSUE THREAD

**Issue by xiruzhu** [anrl/JAM#13]
I am not sure how to fix this but
jwork_process_subsock for async will signal js->atable->globalsem
But the only place which waits this semaphore is inside the event loop.
However when we make J2C async call, it seems despite signalling it, the event loop will never be hit.

**Comment by anrl** [comment]
Is this solved now?

**Comment by xiruzhu** [comment]
uh, right now I am using delay instead of yield. If the delay is set to be too short, it doesn't work.
So it is still a problem within jam if we have to rely on such mechanism.

**Comment by anrl** [comment]
Ok.. May be we can leave the long delay there and you can move to other examples. We look at this issue in depth at the end of the week. I would like to see how the JAMScript model maps into real world apps. So it is better to write some cool simplified applications.

**Comment by anrl** [comment]
I think we finally fixed it. Xiru can you confirm?

**Comment by xiruzhu** [comment]
Ok I will attempt 

    On Saturday, June 11, 2016 2:25 PM, anrl <notifications@github.com> wrote:
 

 I think we finally fixed it. Xiru can you confirm?—

**Comment by anrl** [comment]
Ok.. let me close the very first issue to be closed.
